owner: dtk2 
repo: upptime 

sites:
  - name: AutosUsados Site
    url: http://www.autosusados.cl/
  - name: Tattersall
    url: https://autotattersall.cl/
  - name: Auth Service
    url: https://api.servicesdtk2.cl/v1/auth/_health
  - name: SendMail Service
    url: https://api.servicesdtk2.cl/v1/sendMail/_health
  - name: Cars Service
    url: https://api.servicesdtk2.cl/v1/cars/_health
  - name: ApiAU
    url: https://api-clientes.servicesdtk2.cl/
  - name: Salfa Rent
    url: https://salfausados.cl/usados-rent-a-car/


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://www.autosusados.cl/props-menu-footer/images/logo_agencia01.png
  name: Upptime
  introTitle: "**Agencia Destacados** uptime monitor"
  navbar:
    - title: Status
      href: /
    

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
